# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('pt_dl', models.FloatField(blank=True, null=True)),
                ('pt_ul', models.FloatField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=120, null=True)),
                ('longi', models.CharField(blank=True, max_length=120, null=True)),
                ('dist', models.CharField(blank=True, max_length=120, null=True)),
                ('rb', models.IntegerField(blank=True, null=True)),
                ('mcs', models.IntegerField(blank=True, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deploy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Deployment')),
                ('nvf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Nvf')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
    ]
