# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.CharField(default='41.275621', max_length=120)),
                ('longitude', models.CharField(default='1.986591', max_length=120)),
                ('description', models.TextField(default='description')),
                ('file', models.FileField(blank=True, null=True, upload_to='btss/')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('forecast', models.CharField(blank=True, max_length=500, null=True)),
                ('rb_offer', models.CharField(blank=True, default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=500, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
        migrations.CreateModel(
            name='Bts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('ip', models.CharField(max_length=120)),
                ('lat', models.CharField(max_length=120)),
                ('longi', models.CharField(max_length=120)),
                ('radio', models.IntegerField(blank=True, null=True)),
                ('neighbor', models.CharField(blank=True, max_length=500, null=True)),
                ('BW', models.CharField(blank=True, max_length=500, null=True)),
                ('freCs', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Area')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
        migrations.CreateModel(
            name='OArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('forecast', models.CharField(blank=True, max_length=500, null=True)),
                ('rb_offer', models.CharField(blank=True, default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=500, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Area')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
            ],
        ),
    ]
