# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='end_ceilometer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='end_heat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='end_keystone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='end_nova',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
