# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cluster', models.CharField(blank=True, max_length=20, null=True)),
                ('vnc', models.CharField(blank=True, max_length=200, null=True)),
                ('network', models.CharField(blank=True, max_length=20, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
    ]
